# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

Vagrant.configure(2) do |config|
 
  config.vm.box = "geerlingguy/ubuntu1604"
 
  #Set IP for virtual machine
  config.vm.network "private_network", ip: "192.168.50.5"
  config.ssh.username = 'vagrant'
  config.ssh.password = 'vagrant'
  config.ssh.insert_key = 'true'
  
  # Synced folder
  config.vm.synced_folder "./resources", "/home/vagrant"
  
  # Configuration
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
  end

  # Script to execute after init
  config.vm.provision "shell", inline: "sudo sh install.sh"

end